# templates/services/events-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cinemaabyss.fullname" . }}-events
  labels:
    app: {{ include "cinemaabyss.name" . }}
    chart: {{ include "cinemaabyss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.events.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.events.service.port | default 8080 }}
      targetPort: {{ .Values.events.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "cinemaabyss.name" . }}
    component: events
