{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
        imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyService.service.targetPort }}
        env:
        - name: KONG_DATABASE 
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: /kong/kong.yml
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:{{ .Values.proxyService.service.targetPort }}"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        envFrom:
          - configMapRef:
              name: cinemaabyss-config
          - secretRef:
              name: cinemaabyss-secrets
        resources:
          {{- toYaml .Values.proxyService.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.proxyService.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.proxyService.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: kong-config
          mountPath: /kong
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
      volumes:
        - name: kong-config
          configMap:
            name: kong-config
{{- end }}